sudo: false
language: node_js
node_js:
  - "15"
  - "14"
  - "12"
  - "10"
  - "9"
  - "8"
scripts:
  - "npm test"
matrix:
  allow_failures:
    - node_js: "9"
addons:
  sauce_connect: true
after_success:
  - "npm run test:sauce"
